apiVersion: v1
kind: Service
metadata:
  labels:
    app: 
  name: {{ .Values.deploy.name }}-app
spec:
  type: NodePort
  ports:
    - name: {{ .Values.deploy.name }}-service
      port: 3000
      targetPort: 3000
      nodePort: 31000
  selector:
    app: {{ .Values.deploy.name }}-app
