apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploy.name }}-service
  namespace: {{ .Values.deploy.namespace }}
spec:
  selector:
    app: {{ .Values.deploy.name }}-app
  ports:
  - name: http
    port: 80
    protocol: TCP
    type: NodePort
