apiVersion: v1
kind: Service
metadata:
  name: my-nestjs-project-service
  namespace: stage
spec:
  type: ClusterIP
  selector:
    app: my-nestjs-deployment
  ports:
    - name: http
      port: 3000
      protocol: TCP
      type: NodePort
