apiVersion: v1
kind: Service
metadata:
  name: my-nestjs-project-deployment
spec:
  type: ClusterIP
  selector:
    app: my-nestjs-project-service
  ports:
    - name: http
      port: 3000
      protocol: TCP
