apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploy.name }}-service
  namespace: {{ .Values.deploy.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.deploy.name }}-app
  ports:
    - name: http
      port: 3000
      type: NodePort
