apiVersion: v1
kind: Service
metadata:
  name: my-nestjc-project-service
spec:
  type: ClusterIP
  selector:
    app: my-nestjs-app
  ports:
    - name: http
      port: 3000
      protocol: TCP
      type: NodePort
